In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr



[[8985, 2907, 4909, 8729],
 [8985, 2907, 4909, 3230],
 [8985, 7643, 4909, 4926],
 [51, 1353, 8392, 9185, 6084],
 [51, 1353, 8392, 9185, 2732],
 [4961, 8985, 2900, 4909, 5536],
 [3465, 2277, 1705, 9185]]

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8985 2907 4909 8729]
 [   0    0    0    0 8985 2907 4909 3230]
 [   0    0    0    0 8985 7643 4909 4926]
 [   0    0    0   51 1353 8392 9185 6084]
 [   0    0    0   51 1353 8392 9185 2732]
 [   0    0    0 4961 8985 2900 4909 5536]
 [   0    0    0    0 3465 2277 1705 9185]]


In [8]:
dim=10

In [9]:
model=Sequential()
model.add(Embedding(input_dim=voc_size,output_dim=dim,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [10]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 692ms/step


array([[[-3.3857513e-02,  1.9365225e-02, -2.7896166e-03,  1.3553295e-02,
          3.1021778e-02,  3.0202579e-02,  3.8108196e-02,  2.1286719e-03,
         -5.9670210e-04, -1.1038434e-02],
        [-3.3857513e-02,  1.9365225e-02, -2.7896166e-03,  1.3553295e-02,
          3.1021778e-02,  3.0202579e-02,  3.8108196e-02,  2.1286719e-03,
         -5.9670210e-04, -1.1038434e-02],
        [-3.3857513e-02,  1.9365225e-02, -2.7896166e-03,  1.3553295e-02,
          3.1021778e-02,  3.0202579e-02,  3.8108196e-02,  2.1286719e-03,
         -5.9670210e-04, -1.1038434e-02],
        [-3.3857513e-02,  1.9365225e-02, -2.7896166e-03,  1.3553295e-02,
          3.1021778e-02,  3.0202579e-02,  3.8108196e-02,  2.1286719e-03,
         -5.9670210e-04, -1.1038434e-02],
        [-1.3696026e-02,  4.8228789e-02,  8.8667497e-03, -3.9840281e-02,
          2.3910474e-02, -4.5353901e-02, -4.2871799e-02,  2.8886463e-02,
         -2.0474697e-02,  1.2366317e-02],
        [-4.6010613e-02, -3.1942785e-02,  1.5761886e-02, -1.

In [12]:
model.predict(embedded_docs[0:1])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step


array([[[-0.03385751,  0.01936522, -0.00278962,  0.0135533 ,
          0.03102178,  0.03020258,  0.0381082 ,  0.00212867,
         -0.0005967 , -0.01103843],
        [-0.03385751,  0.01936522, -0.00278962,  0.0135533 ,
          0.03102178,  0.03020258,  0.0381082 ,  0.00212867,
         -0.0005967 , -0.01103843],
        [-0.03385751,  0.01936522, -0.00278962,  0.0135533 ,
          0.03102178,  0.03020258,  0.0381082 ,  0.00212867,
         -0.0005967 , -0.01103843],
        [-0.03385751,  0.01936522, -0.00278962,  0.0135533 ,
          0.03102178,  0.03020258,  0.0381082 ,  0.00212867,
         -0.0005967 , -0.01103843],
        [-0.01369603,  0.04822879,  0.00886675, -0.03984028,
          0.02391047, -0.0453539 , -0.0428718 ,  0.02888646,
         -0.0204747 ,  0.01236632],
        [-0.04601061, -0.03194278,  0.01576189, -0.0107766 ,
          0.00256936,  0.02482295, -0.02634843,  0.04097537,
         -0.01377143, -0.00577909],
        [ 0.02225138,  0.00328892,  0.04115281, -0.0